force user to enter password until it works

diff --git a/homework/midterm/addloginid b/homework/midterm/addloginid
--- a/homework/midterm/addloginid
+++ b/homework/midterm/addloginid
@@ -224,8 +224,10 @@ function main() {
     # Expire password.
     passwd -e ${username}
 
-    # Change password.
-    passwd ${username}
+    # Change password while password changing fails.
+    while ! passwd ${username}; do
+        echo "Failed to set password. Try again."
+    done
 
     echo "username=${username};GID=${group_id};UID=${user_id} is set up!"
 
